### ISSUE TITLE
Version 3.0.0 Roadmap

### ISSUE THREAD

**Issue by maddin77** [BreadfishPlusPlus/BreadfishPlusPlus#26]
- [x] Umschreiben des gesamten Codes auf [browserify](http://browserify.org/)
- [x] Einstellungen
  - [x] Importieren/Exportieren
  - [x] **Allgemeine Einstellungen**
    - [x] _Erweiterungen_
      - [x] Alternative PN Benachrichtigung
      - [x] Asynchrone Datenübertragung
      - [x] Alternative Tooltips
      - [x] Spitznamen für Benutzer
      - [x] Meldungsgründe
      - [x] Relative Zeitangaben
    - [x] _Fehlerbehebungen_
      - [x] Header-Fix
      - [x] Expander
      - [x] Tabmenu
      - [x] Bildverkleinerung
    - [x] _Filter_
      - [x] Ankündigungen
    - [x] _Debug_
      - [x] Debugmode 
  - [x] **Forenübersicht**
    - [x] _Erweiterungen_
      - [x] Die letzten X Beiträge
      - [x] IRC Shoutbox
    - [x] _Fehlerbehebungen_
      - [x] Suche Icon
    - [x] _Filter_
      - [x] Zur Zeit sind X Benutzer online
      - [x] Statistik
      - [x] Geburtstage
  - [x] **Themenübersicht**
    - [x] _Erweiterungen_
      - [x] Ankündigungen und wichtige Themen trennen
    - [x] _Filter_
      - [x] Gelöschte Themen
  - [x] **Beiträge & Nachrichten**
    - [x] _Erweiterungen_
      - [x] Kurz-URL
      - [x] Youtube Vorschau
      - [x] Danksagungen anzeigen
      - [x] Höhenbegrenzung für Signaturen
      - [x] Bilderzoom
      - [x] Deaktivierung von externen Bildern
      - [x] Syntaxhervorhebung
      - [x] ~~Lazyload~~
    - [x] _Filter_
      - [x] Youtube-Videos
      - [x] Gelöschte Beiträge
      - [x] Bedankomat
      - [x] Ignorierte Benutzer
      - [x] Hilfreichste Antwort
      - [x] Beitragscounter
      - [x] Benutzertitel
      - [x] Benutzerrang
      - [x] Zusätzlicher Benutzerrang
      - [x] Registrierungsdatum
      - [x] Geschlecht
      - [x] XBL Gamertag
      - [x] PSN ID
      - [x] Steam
      - [x] Origin
      - [x] Website
      - [x] ICQ
      - [x] Windows Live
      - [x] Skype
  - [x] **Beitrag/Nachrichten erstellen**
    - [x] _Erweiterungen_
      - [x] Benutzer-Autovervollständigung
    - [x] _Smilies_
      - [x] Rageicons
      - [x] Skype
      - [x] Y o l k s
      - [x] Emoji
    - [x] _BBCodes_
      - [x] E-Mail
      - [x] Text tiefstellen
      - [x] Text hochstellen
      - [x] Java-Quelltext
      - [x] Cascading Style Sheet
      - [x] HTML
      - [x] XML
      - [x] Javascript-Quelltext
      - [x] C/C++-Quelltext
      - [x] Dropdown
      - [x] Sevenload
      - [x] Clipfish
      - [x] Googlevideo
      - [x] MySpace
      - [x] MyVideo
  - [x] **Benutzerprofil**
    - [x] _Filter_
      - [x] Danksagungen
      - [x] Beitragscounter
      - [x] Benutzertitel
      - [x] Benutzerrang
      - [x] Zusätzlicher Benutzerrang
      - [x] Geschlecht
      - [x] Registrierungsdatum
      - [x] Über Mich
      - [x] Geburtstag
      - [x] Wohnort
      - [x] Beruf
      - [x] Hobbys
      - [x] Teamspeak UID
      - [x] XBL Gamertag
      - [x] PSN ID
      - [x] Steam
      - [x] Origin
      - [x] Website
      - [x] ICQ
      - [x] Windows Live
      - [x] Skype
  - [x] **Tastaturnavigation**
    - [x] Vorheriger Post
    - [x] Nächster Post
    - [x] Vorherige Seite
    - [x] Nächste Seite
- [x] Userscript support
- [x] Google Chrome Erweiterung
- [x] Mozilla Firefox AddOn
- [x] Opera Erweiterung
- [x] Safari Extension
- [x] Benachrichtigung bei Privater nachricht sollte auch auf eigene Ordner zurückgreifen
- [x] Benutzer-Autovervollständigung überarbeiten (#22, #23, #25)
- [x] User Tagging (#24)
- [x] Zitat-Benachrichtigung (#21)
- [x] Ankündigungen & Wichtige Themen nicht trennen wenn nur eins der beiden da ist (#13)
- [x] [Teamspeak Viewer](https://cloud.githubusercontent.com/assets/183928/3489823/078e40a6-0548-11e4-9f5e-5bfe258433ed.png)
- [x] Zusätzliche Anzeige wenn eine Option geändert & gespeichert wurde.
